### ISSUE TITLE
No module name argparse

### ISSUE THREAD

**Issue by jshy** [ARDroneSDK3/ARSDKBuildUtils#11]
While trying to build on Ubuntu Linux - Linux 2.6.32-46-generic #107-Ubuntu SMP
~/SDK/ARSDKBuildUtils$ ./SDK3Build.py -t Unix

Looking in the Utils/Python directory I don't see an argsparse file either.
Traceback (most recent call last):
  File "./SDK3Build.py", line 57, in <module>
    import commandLine
  File "/home/jesse/SDK/ARSDKBuildUtils/Utils/Python/commandLine.py", line 32, in <module>
    import argparse
ImportError: No module named argparse

**Comment by N-Bz** [comment]
Hi,

It seems that your python installation is too old for the SDK. The `argparse` module is included in python 2.7 and higher, and is indeed required by the SDK3Build.py script.

You can check your python version by running `python --version`. If it's lower than 2.7.x, you'll need to upgrade it before you can build the SDK.

Regards,
Nicolas.

**Comment by jshy** [comment]
Thanks.
