### ISSUE TITLE
Linking the frameworks in xcode?

### ISSUE THREAD

**Issue by M0rph3v5** [ARDroneSDK3/ARSDKBuildUtils#12]
I've dropped all the built frameworks in a fresh iOS project, however it fails to compile. Exits with:

```
ld: framework not found libmavlink
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

any specific way to link?

**Comment by djavan-bertrand** [comment]
Hi M0rph3v5, 

Please see the sample [RollingSpiderPiloting](https://github.com/ARDroneSDK3/Samples/tree/master/iOS/RollingSpiderPiloting) to have a working example of an iOS app using the SDK.

Regards, 
Djavan
