### ISSUE TITLE
How to connect to Be Boop from iOS app?. 

### ISSUE THREAD

**Issue by CesarRN** [ARDroneSDK3/ARSDKBuildUtils#17]
Hello Bebob SDK Team.

I´m trying to develop an iPhone app.

I read the RollingSpider example project.
The Be Boop hash´t have bluetooth.

How can I do a wifi connection to the drone from iOS-App?

Thanks in advance.

**Comment by djavan-bertrand** [comment]
Hi, 

The sample is available [here](https://github.com/ARDroneSDK3/Samples/tree/master/iOS/BebopDronePiloting).

Cheers, 
Djavan
