### ISSUE TITLE
SDK3Build.py fails to build the Android target

### ISSUE THREAD

**Issue by cipriansofronia** [ARDroneSDK3/ARSDKBuildUtils#18]
So.. I did exactly as it says in https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL
But every time I run SDK3Build.py, it fails to build the libraries I need for Android.. 

In my /etc/bash.bashrc I properly configured the environment variables, ANDROID_SDK_PATH and
 ANDROID_NDK_PATH and every time I run echo $ANDROID_SDK_PATH I get the correct path (someting like that: /media/windows/install/Android/Sdk).. but in SDK3Build.py it says that ANDROID_SDK_PATH and ANDROID_NDK_PATH must be set to build.. 
I tried every solution I found on Google.. but I can't make it work.. Any ideas?

If I run ./CheckEnv.py I get the following: http://pastebin.com/jvxm6iAT
And if I run sudo ./SDK3Build.py -t Android I get this: http://pastebin.com/DDQtpRNb
My environment variables from /etc/bash.bashrc are configured like that: http://pastebin.com/HG7u8HLY

Thanks!

**Comment by N-Bz** [comment]
Hi,

Your setup seems fine, but it seems that the bashrc modifications are not visible in your build shell.

Have you tried running the `./SDK3Build.py -t Android` command in a "new" shell (Or the shell in which you ran the CheckEnv.py script) ? So you're sure that your bashrc is properly sourced.

Regards,
Nicolas

**Comment by cipriansofronia** [comment]
So.. I ran ./SDK3Build.py -t Android.. all good now with the environment variables.. 
But, this time I get something like this: http://pastebin.com/bnDNeDd9

It seems like it can't find some config files from "libARSAL/Build/config".. what's wrong now? 

Thanks!

**Comment by N-Bz** [comment]
The issue might come from the fact that you ran the build script as superuser once, and some generated files are not readable by your own user.

You can try to run `sudo ./SDK3Build.py --nogit --all-cleanup` to force deleting all generated files, then build again without `sudo`.

If this solution does not work, the "easiest" (but longer) solution would be to delete your SDK copy and make a fresh clone.

**Comment by cipriansofronia** [comment]
It seems like the first solution worked for me.. This time it build most of the libraries I need, excepting json, ARUpdater and ARMedia.. I'll try later to make a fresh clone.. and then it might build all the libs.

Thank you for all the support!
