### ISSUE TITLE
Hovering for Bebop

### ISSUE THREAD

**Issue by daqo** [ARDroneSDK3/ARSDKBuildUtils#19]
I am writing a C program for basic navigation of Bebop drone. After taking off, what should I do to drone hover stably in a place?

**Comment by djavan-bertrand** [comment]
Before taking off, you have to send ARCOMMANDS_Generator_GenerateCommonCommonAllStates to get all the states. 
Please see [this related issue](https://github.com/ARDroneSDK3/Samples/issues/17#issuecomment-81615805).

Best regards, 
Djavan
