### ISSUE TITLE
Saving pictures from Rolling Spider

### ISSUE THREAD

**Issue by katho** [ARDroneSDK3/ARSDKBuildUtils#31]
Hello everyone, I'm trying to save pictures taken from the Rolling Spider. In the documentation the method needs a byte value to save in the drone or to save to the device. The thing is the values are not specified, ¿can you help me with this one?

Thanks in advance.

**Comment by djavan-bertrand** [comment]
Hi, 
This mass storage id is not used, it will be removed in the near future.
You can pass 0.

The RollingSpider save the picture on its own internal memory. To get the picture, you need to transfer the picture on your device thanks to libARDataTransfer. Please see this [related issue](https://github.com/ARDroneSDK3/Samples/issues/29#issuecomment-84709358).

Regards, 
Djavan

**Comment by katho** [comment]
Hello, 
Thanks a lot, I'm on it.
