### ISSUE TITLE
JumpingSumo cmd

### ISSUE THREAD

**Issue by GwenLG** [ARDroneSDK3/ARSDKBuildUtils#6]
Hello everyone,

I am master student in France, working on a project which consist to pilot a Jumping Sumo drone with my voice.
At this time I am just looking for how sent command to my drone. I already succeeded to do this with an ARDrone on Linux ( send AT command )
I would like to know if it is the same kind of command I have to send to my Jumping Sumo ?
And am I the only one who trying to create a project on this kind of drone ?

Thanks,

Sorry for my english.

**Comment by N-Bz** [comment]
Hi,

The ARDrone SDK 3 (Compatible with Bebop Drone, Jumping Sumo and Rolling Spider) is really different from the ARDrone SDK 1&2 (Compatible with AR.Drone and AR.Drone 2.0).

We changed all the network code, so you will need to start a new application from scratch to command a Jumping Sumo.

Commands are no longer in the AT* format, and are now binary commands (called "ARCommands" in the SDK) (See [libARCommands](https://github.com/ARDroneSDK3/libARCommands/)).

Regards,
